'use client';
import { useState, useEffect } from 'react';
import { ReportData } from '@/lib/agents/report-agent';

interface Props {
  data: ReportData;
  farmerName: string;
}

export default function ReportPDFButton({ data, farmerName }: Props) {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    // Load jsPDF from CDN dynamically
    if (typeof window !== 'undefined' && !window.hasOwnProperty('jspdf')) {
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
      script.async = true;
      script.onload = () => {
        const autoTableScript = document.createElement('script');
        autoTableScript.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.28/jspdf.plugin.autotable.min.js';
        autoTableScript.async = true;
        autoTableScript.onload = () => setIsLoaded(true);
        document.body.appendChild(autoTableScript);
      };
      document.body.appendChild(script);
    } else {
      setIsLoaded(true);
    }
  }, []);

  const downloadPDF = () => {
    // @ts-ignore
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. Header & Branding
    doc.setFillColor(15, 45, 25); // Dark Green
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('SUPERFARMER ADVISORY', 15, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`CERTIFIED CROP ADVISORY REPORT • ${new Date().toLocaleDateString()}`, 15, 30);

    // 2. Farmer Summary
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Farmer: ${farmerName}`, 15, 55);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(data.sections.farmer_summary, 15, 65, { maxWidth: pageWidth - 30 });

    // 3. Crop Lifecycle Table
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('CROP LIFECYCLE: SEEDING TO HARVEST', 15, 85);

    const lifecycleBody = data.crop_lifecycle.map(phase => [
      phase.phase,
      phase.duration,
      phase.status,
      phase.outcome_goal
    ]);

    // @ts-ignore
    doc.autoTable({
      startY: 90,
      head: [['Phase', 'Duration', 'Status', 'Outcome Goal']],
      body: lifecycleBody,
      headStyles: { fillColor: [22, 101, 52] },
      styles: { fontSize: 9, cellPadding: 5 },
      columnStyles: { 3: { cellWidth: 70 } }
    });

    // 4. Strategic Analysis
    // @ts-ignore
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('STRATEGIC ADVISORY', 15, finalY);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const splitReport = doc.splitTextToSize(data.report.replace(/\*\*/g, ''), pageWidth - 30);
    doc.text(splitReport, 15, finalY + 10);

    // 5. Action Items List
    const actionY = finalY + 10 + (splitReport.length * 5) + 10;
    if (actionY < 270) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('IMMEDIATE ACTION ITEMS:', 15, actionY);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      data.sections.action_items.forEach((item, i) => {
        doc.text(`• ${item}`, 20, actionY + 10 + (i * 7));
      });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('This report is generated by SuperFarmer Agentic AI. Always verify with local agricultural experts.', pageWidth / 2, 285, { align: 'center' });

    doc.save(`SuperFarmer_Advisory_${farmerName.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <button 
      onClick={downloadPDF}
      disabled={!isLoaded}
      className="btn btn-primary"
      style={{ 
        background: isLoaded ? 'linear-gradient(135deg, #16a34a, #15803d)' : '#333', 
        boxShadow: isLoaded ? '0 4px 14px rgba(22, 163, 74, 0.4)' : 'none',
        fontWeight: 700,
        gap: '0.5rem',
        display: 'flex',
        alignItems: 'center',
        opacity: isLoaded ? 1 : 0.7,
        cursor: isLoaded ? 'pointer' : 'not-allowed'
      }}
    >
      {isLoaded ? '📄 Download Official PDF Report' : '⌛ Preparing PDF Engine...'}
    </button>
  );
}
