// src/lib/agents/replanner-agent.ts
// DynamicReplannerAgent — autonomously triggered by NutrientAgent when risk is HIGH
// Updates the crop plan with emergency interventions without user input

import { getJsonModel, withTimeout } from '@/lib/gemini';
import { dbExecute } from '@/lib/fluxbase';
import { saveMemory } from './context';
import type { AgentContext, AgentResult } from './types';

export interface ReplannerData {
  status: string;
  emergency_actions: string[];
  updated_irrigation: string;
  updated_fertilizer: string;
  reason: string;
}

const SYSTEM_INSTRUCTION = `You are an Emergency Agricultural Replanning Agent.
When a farmer's crop is at HIGH nutrient risk, you autonomously update their crop plan with urgent corrective actions.
Be specific, actionable, and urgent. Use exact quantities and timings.
Respond only with valid JSON.`;

export async function runReplannerAgent(
  ctx: AgentContext,
  riskData: { risk_level: string; risk_probability: number; suggestion: string; n: number; p: number; k: number }
): Promise<AgentResult<ReplannerData>> {
  const trace: string[] = [];
  const { farmerId, planId, farmerProfile } = ctx;

  trace.push('DynamicReplanner triggered: HIGH nutrient risk detected.');

  // ── Step 1: Load current plan ──
  trace.push('Step 1: Loading current crop plan from database...');
  let currentPlan: Record<string, unknown> = {};
  if (planId) {
    const planRows = await dbExecute('SELECT * FROM crop_plans WHERE plan_id = ?', [planId]);
    if (planRows[0]) currentPlan = planRows[0];
  } else if (farmerId) {
    const planRows = await dbExecute(
      'SELECT * FROM crop_plans WHERE farmer_id = ? ORDER BY created_at DESC LIMIT 1',
      [farmerId]
    );
    if (planRows[0]) currentPlan = planRows[0];
  }
  const cropName = (currentPlan.crop_name as string) || 'Unknown crop';
  trace.push(`Step 1 ✓: Loaded plan for crop: ${cropName}`);

  // ── Step 2: Call Gemini for emergency replan ──
  trace.push('Step 2: Calling AI for emergency intervention plan...');
  let replan: ReplannerData;

  try {
    const model = getJsonModel(SYSTEM_INSTRUCTION, { temperature: 0.15, maxTokens: 700 });
    const userPrompt = `URGENT: Crop at HIGH nutrient risk.

Crop: ${cropName}
Location: ${farmerProfile?.location || 'India'}
Current NPK: N=${riskData.n}, P=${riskData.p}, K=${riskData.k}
Risk Probability: ${riskData.risk_probability}%
AI Suggestion: ${riskData.suggestion}

Current Plan:
- Irrigation: ${currentPlan.irrigation_plan || 'Unknown'}
- Fertilizer: ${currentPlan.fertilizer_schedule || 'Unknown'}

Generate an emergency replanning response:
{
  "status": "Emergency Updated",
  "emergency_actions": ["action 1 with exact quantities", "action 2", "action 3"],
  "updated_irrigation": "revised irrigation schedule specific to this risk",
  "updated_fertilizer": "specific fertilizer doses with timing to correct deficiency",
  "reason": "why these interventions address the specific N/P/K imbalance"
}`;

    const result = await withTimeout(model.generateContent(userPrompt), 20_000);
    replan = JSON.parse(result.response.text()) as ReplannerData;
    trace.push('Step 2 ✓: Emergency intervention plan generated by AI.');
  } catch (err) {
    trace.push(`Step 2 ✗: AI failed — using rule-based emergency interventions.`);
    console.error('ReplannerAgent error:', err);
    replan = {
      status: 'Emergency Updated',
      emergency_actions: [
        'Apply 25kg/acre Urea immediately via foliar spray or soil application',
        'Irrigate twice daily for next 3 days to activate nutrients',
        'Scout field for visible deficiency symptoms every 12 hours',
      ],
      updated_irrigation: 'Irrigate every 2 days for next 7 days. Do not allow moisture drop below 40%.',
      updated_fertilizer: `Emergency: Apply NPK 20:20:0 at 20kg/acre. Follow with Potash (MOP) if K<30.`,
      reason: `Detected low NPK levels (N=${riskData.n}, P=${riskData.p}, K=${riskData.k}) at high risk probability ${riskData.risk_probability}%.`,
    };
  }

  // ── Step 3: Update crop plan in DB ──
  trace.push('Step 3: Updating crop plan in database with emergency interventions...');
  const newIrrigation = `[EMERGENCY] ${replan.updated_irrigation}`;
  const newFertilizer = `[EMERGENCY] ${replan.updated_fertilizer}\n\nEmergency Actions:\n${replan.emergency_actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}`;

  if (currentPlan.plan_id) {
    await dbExecute(
      'UPDATE crop_plans SET irrigation_plan = ?, fertilizer_schedule = ?, status = ? WHERE plan_id = ?',
      [newIrrigation, newFertilizer, 'Emergency Updated', currentPlan.plan_id]
    );
    trace.push(`Step 3 ✓: Plan #${currentPlan.plan_id} updated with emergency interventions.`);
  }

  // ── Step 4: Save memory ──
  if (farmerId) {
    void saveMemory(
      farmerId,
      'replanner',
      `HIGH risk triggered emergency replan for ${cropName}. Risk: ${riskData.risk_probability}%. Actions: ${replan.emergency_actions[0]}`
    );

    // Log to nutrient_risk_log
    void dbExecute(
      'INSERT INTO nutrient_risk_log (farmer_id, plan_id, risk_probability, risk_level, suggested_action) VALUES (?, ?, ?, ?, ?)',
      [farmerId, currentPlan.plan_id || null, riskData.risk_probability, 'High', replan.emergency_actions.join('; ')]
    );
  }
  trace.push('Step 4 ✓: Memory saved. Nutrient risk logged.');

  return {
    success: true,
    data: replan,
    trace,
    triggered: 'replanner-agent', // Flag so the response shows the replanner was auto-triggered
  };
}
